### ISSUE TITLE
Swift 2.0 and XCode 7: Use of undeclared type 'OLFacebookImagePickerControllerDelegate'

### ISSUE THREAD

**Issue by 25matt12** [OceanLabs/FacebookImagePicker-iOS#12]
Hi,

I tried to implement your library in my project using swift 2.0 and XCode 7 but when I try to compile I get the following error message: "Use of undeclared type 'OLFacebookImagePickerControllerDelegate'".

I double checked my bridging header but everything seems to look fine, I use other libraries that are included in this header and to be sure I included every .h that I found:

    #import <FacebookImagePicker/OLFacebookImagePickerController.h>
    #import <FacebookImagePicker/OLFacebookAlbumRequest.h>
    #import <FacebookImagePicker/OLFacebookPhotosForAlbumRequest.h>
    #import <FacebookImagePicker/OLFacebookAlbum.h>
    #import <FacebookImagePicker/OLFacebookImage.h>
    #import <FacebookImagePicker/OLFacebookImagePickerController.h>

I included the library using cocapod (0.39.0.beta.4) using "use_frameworks!" flag and targeting iOS 8.0.
I tried to compile the application under the iPhone 6s simulator on iOS 8.0.

When I use "import FacebookImagePicker" it looks like everything is working but when the controller loads it shows me nothing except a black screen with a navigationBar titled "Photos" and a "done" button.

If I try to touch the button nothing happens ...

I specify that the controller that launch the pickerViewController has inherited from the OLFacebookImagePickerControllerDelegate and UINavigationControllerDelegate protocols and is set delegate of the pickerViewController.

I tried to print something in all the protocol's method I could implement but nothing is showing up and my user is already logged in the app with facebook SDK 4.6.0

Do you have any idea of what is happening ? Did I made a mistake including the library ?

Thank you.

**Comment by mlequeux** [comment]
Hi, I had the same problems, here is what you need to make it work :

In your bridging header you only need to add : 
```
#import <FacebookImagePicker/OLFacebookImagePickerController.h>
```

Then your Swift class needs to conforms to the following protocols :
```
OLFacebookImagePickerControllerDelegate, UINavigationControllerDelegate 
```

To make the done (and the cancel button working), you need to dismiss yourself the imagePicker :
```
    func facebookImagePicker(imagePicker: OLFacebookImagePickerController!, didFinishPickingImages images: [AnyObject]!) {
        ...
        self.imagePicker.dismissViewControllerAnimated(true, completion: nil)
    }
    
    func facebookImagePickerDidCancelPickingImages(imagePicker: OLFacebookImagePickerController!) {
        ...
        self.imagePicker.dismissViewControllerAnimated(true, completion: nil)
    }
```
Finally you need a bit of checking due to swift code generation if you want to limit the number of selectable images (This is for one image max):
```
    func facebookImagePicker(imagePicker: OLFacebookImagePickerController!, shouldSelectImage image: OLFacebookImage!) -> Bool {
        if imagePicker.selected == nil {
            return true;
        } else if imagePicker.selected.count == 0 {
            return true;
        } else {
            return false;
        }
    }
```

Also, if nothing is displayed, try to check on the FB Graph Explorer for the following query using your Facebook token :
```
me/albums?limit=100&fields=id,name,count,cover_photo
```
If the resulting array is empty, that's probably because you forgot to add the **user_photos** permission at the time of login in your app.

**Comment by 25matt12** [comment]
Okay, so I finally found the origin of the issue and it was because there was a bug when using the library in swift with cocoapods and the "use frameworks!" flag.

The owner has committed an update and now everything is working properly ! :)

Thanks.
