### ISSUE TITLE
Facebook callback not being called - RESOLVED

### ISSUE THREAD

**Issue by RitvikM** [OceanLabs/FacebookImagePicker-iOS#13]
When I use the library i get a message saying that I ahve already authorized the app, and then when i click okay, it goes immediately dismisses the photo picker view, and I can never get too it. 

Also the HuggleUp App doesn't seem to show up images on the picker view, its just empty. After dismissing the empry picker view by clicking 'Done' it crashes. I am using an iPhone 6S with iOS 9.1

**Comment by RitvikM** [comment]
it looks like the callback in line 53 of FacebookImagePickerController.m, isn't being called, after a user authorizes the app on FB

if( imp ) imp(login, aSelector, permissions, self, ^(id result, NSError *error) {

**Comment by RitvikM** [comment]
this was caused because I did not include the following code in my AppDelegate: 

- (BOOL)application:(UIApplication *)application
             openURL:(NSURL *)url
   sourceApplication:(NSString *)sourceApplication
          annotation:(id)annotation {
   return [[FBSDKApplicationDelegate sharedInstance] application:application
                                                         openURL:url
                                               sourceApplication:sourceApplication
                                                      annotation:annotation];
}


Please mark this issue as closed. 


The HuggleUp App bug still exists though.

**Comment by dbotha** [comment]
@ritvikm glad to hear that worked for you, I'll make a note to call out the step more clearly in the documentation! HuggleUp needs and update after which the issue you're seeing should disappear!
