### ISSUE TITLE
Upgrade to Facebook SDK 4.0

### ISSUE THREAD

**Issue by julien-c** [OceanLabs/FacebookImagePicker-iOS#2]
Hi,

I'd be willing to look into upgrading the FB SDK to 4.0 if you'd be ok with it.

I'm not sure at this point whether the upgrade would mean changing many things or not (but I suspect not). See the high-level changelog here: https://developers.facebook.com/docs/ios/upgrading-4.x

Any thoughts?

Cheers!

**Comment by dbotha** [comment]
Hi Julien,

Wow surprised people are using this before I even got any README up (soon!). Hoping it's working out well for you? Sure please do, I don't think it'd require much change to work with the new API but I've not had the chance to take a peek yet. If you create a pull request I'll happily review and merge.

Thanks

**Comment by dbotha** [comment]
btw, LOVE circular.io :) :+1: Use it frequently.

**Comment by julien-c** [comment]
Ha, that's great! :beers: 

It worked perfectly once I set up another Facebook app ID (the one included in the project had Facebook complain about Sign-in not being enabled, I believe). By the way I found it while searching Cocoapods for Image Picker. Ok I'll try and give it a go then!

**Comment by cashmash** [comment]
trust me, more people will use this lib

**Comment by julien-c** [comment]
I will look into this today or tomorrow @dbotha

**Comment by dbotha** [comment]
Awesome :) I'm picking up the start of the documentation this weekend so that the library is a little more approachable.

**Comment by julien-c** [comment]
You're not planning on writing the lib in Swift by the way, are you? :)

**Comment by dbotha** [comment]
Not on the roadmap just yet, my Swift work has purely been SpriteKit game development related up until recently — need to get educate myself on everything else first :)

**Comment by julien-c** [comment]
See PR in #3

**Comment by dbotha** [comment]
Hi @julien-c , awesome I'll be taking a look at this sometime over the next few days!

**Comment by julien-c** [comment]
Great! Let me know if you need any help.

**Comment by dbotha** [comment]
Hey @julien-c , not forgotten about this - just haven't found the time to do a proper review yet. I'm hoping later this week!

**Comment by julien-c** [comment]
Sure. Let me know if any help needed!

**Comment by styrken** [comment]
Hey,

It would be awesome if the PR could be accepted.

**Comment by dbotha** [comment]
Hey guys, sorry it really is on my list of things to do. I'll try my very best to get it done within the next week.

**Comment by styrken** [comment]
Great.

I have looked a bit into the PR and @julien-c is missing a rewrite of OLFacebookPhotosForAlbumRequest as well. He only fixed loading the album list.

**Comment by julien-c** [comment]
Hmm, `PhotosForAlbum` works for me and I've been running this in production for more than two months now :)

**Comment by cashmash** [comment]
any update :)?

**Comment by cashmash** [comment]
any update?

**Comment by dbotha** [comment]
@kkarayannis has done some work to review @julien-c pull request and this should now be complete.
