### ISSUE TITLE
PodSpec Bump

### ISSUE THREAD

**Issue by hangryfabian** [OceanLabs/FacebookImagePicker-iOS#24]
Hi, 

Can someone with write access please bump the Facebook dependencies to 4.10 from 4.08. I'd prefer  to use cocoapods rather than adding the code directly to my source code, and I can't do that as our app uses the latest facebook sdk 4.10.

Thanks!

**Comment by hernangonzalez** [comment]
You can fork it and do it your self. I have done that and send a PR btw.

**Comment by hangryfabian** [comment]
Thanks! I didn't know how use cocoapods to my own fork. I got it working now though.
