### ISSUE TITLE
no multiple selection !

### ISSUE THREAD

**Issue by hagile** [OceanLabs/FacebookImagePicker-iOS#5]
Is there a way to stop multiple selection from albums. Currently user can able to select multiple photos. Its not in requirement for me,  so is there a direct way with your library to achieve this? If you didn't implemented such thing then also let me know, in which class and method I will able to stop it? I'll surely look by my self.

Thanks a ton for such a good work !! +1

**Comment by khanamir** [comment]
@dbotha please help in this regard.

**Comment by hagile** [comment]
I'm able to make it work like this,

Change this method in `OLPhotoViewController.m` file.

    -(void) collectionView:(UICollectionView *)collectionView didSelectItemAtIndexPath:(NSIndexPath *)indexPath {
        //[self updateTitleWithSelectedIndexPaths:collectionView.indexPathsForSelectedItems];
        [self onButtonDoneClicked];
    }

**Comment by dbotha** [comment]
@khanamir agree it needs to be fixed in the library itself, sorry I've been incredibly busy as of late. I'll try get round to fixing it soon.

**Comment by hagile** [comment]
@dbotha, have you ever get time to update it?

**Comment by kkarayannis** [comment]
This is now possible. Take a look in the last paragraph of the usage section: https://github.com/OceanLabs/FacebookImagePicker-iOS#usage
