### ISSUE TITLE
Bizzarre linker errors if integrated in project without cocoa pods (old fashioned way)

### ISSUE THREAD

**Issue by khanamir** [OceanLabs/FacebookImagePicker-iOS#6]
@dbotha My requirement is to display the chosen image in fullscreen so that the user could further confirm the selected image or cancel it (like the native image picker in iOS). I removed the pod for FacebookImagePicker-iOS from my project and tried to add it manually (added other depends including Facebook SDK and SDWebImage through pods), but doing so generates 6-7 duplicate symbol linker errors for all the constants defined in OLFacebookImagePickerConstants.h. Googled it, tried all the possible ways but can't get rid of errors.

Could you please help in this regard?

**Comment by dbotha** [comment]
Oh sure, in the OLFacebookImagePickerConstants.h add "extern" to the front:

    extern NSString *const kOLErrorDomainFacebookImagePicker;
    extern const NSInteger kOLErrorCodeFacebookImagePickerBadResponse;
    extern const NSInteger kOLErrorCodeFacebookImagePickerNoOpenSession;

Should do the trick. I'll fix this in the SDK

**Comment by khanamir** [comment]
thanks for the quick reply, but still generating following errors...

![screen shot 2015-05-26 at 5 39 17 pm](https://cloud.githubusercontent.com/assets/10783537/7812693/48e6106c-03ce-11e5-87ee-9832f9b519e7.png)

**Comment by dbotha** [comment]
Great :)

**Comment by budhead** [comment]
Can you update the repository and CocoaPods too?
Now I have to fork or edit the cod inline which is not cool.
