### ISSUE TITLE
OLFacebookImage data

### ISSUE THREAD

**Issue by realsurfer** [OceanLabs/FacebookImagePicker-iOS#8]
Hi,

First of all thank you for a great picker!
Looks like the source field that is used for fullURL is deprecated.
It would also be nice to retrieve the photo id.

Thanks!

**Comment by orenk86** [comment]
Agreed. Is there any way to get the photo id?

**Comment by orenk86** [comment]
Hi @realsurfer , 
Just in case you still need this, I have forked this repository and added the photo id to the OLFacebookImage object.
I have also issued a pull request so my code can be merged into this repository, but until that heppens - you're more than welcome to use mine:

https://github.com/orenk86/FacebookImagePicker-iOS

**Comment by orenk86** [comment]
UPDATE: My pull request has just been merged, we can close this issue now... :)
